Fix hover
Kozaki01/2023_04_cteam pull request #46
Opened 2023-06-23 01:49 UTC by Kozaki01

ホバーの追加と文字の部分にホバーが出ないようにしました

2023-06-26 04:51 UTC, ishiki11 commented on moriworks/src/pages/signup.tsx
> +
変な空白行

2023-06-26 04:55 UTC, ishiki11 requested changes
変更お願いします

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/Header/Header.tsx
> +
空白行

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/Header/Header.tsx
> +
ここも

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/Header/Header.tsx
> +
ここも

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/Pagination/Pagination.tsx
完成済みじゃないなら外してほしい

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/Signup/Signup.tsx
> +
ここも空白行

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/components/index/TopButton/TopButton.module.scss
> +
ここも空白行

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/pages/Pagination.tsx
完成済みのファイルか

2023-06-26 04:55 UTC, ishiki11 commented on moriworks/src/pages/index.tsx
> +
何の空白？

2023-06-26 05:01 UTC, ishiki11 approved these changes

2023-06-27 02:19 UTC, t-dounoma approved these changes

2023-06-27 02:57 UTC, ishiki11 approved these changes

2023-06-27 02:58 UTC, t-dounoma approved these changes

2023-06-27 03:08 UTC, merged